stages:
  - build
  - release

build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: normal 
  before_script:
    - git submodule update --remote
  script: bash ./ci-build.sh 
  tags:
    - jcfwb-1
  except:
    - tags
release:
  stage: release
  variables:
    GIT_SUBMODULE_STRATEGY: normal 
  before_script:
    - git submodule update --remote
    - echo -e "$CI_COMMIT_TAG"
  script:  bash ./ci-build.sh && bash ./ci-release.sh
  tags:
    - jcfwb-2
  only :
    - tags